# Default language English
en:
  languageCode: en-us
  contentDir: content/en  # 영어 콘텐츠는 content/en 폴더에 저장

# Korean (한국어)
ko:
  languageCode: ko-kr
  contentDir: content/ko  # 한국어 콘텐츠는 content/ko 폴더에 저장
