languages:
  ko:
    languageName: "Korean"
    weight: 1
    contentDir: "content/ko"
    title: "내 사이트 (한국어)"
    menu: main

  en:
    languageName: "English"
    weight: 2
    contentDir: "content/en"
    title: "My Site (English)"
    menu: main
