languages:
  ko:
    languageName: "Korean"
    languageCode: "ko"
    weight: 1
    contentDir: "content/ko"
    title: "내 사이트 (한국어)"
    menu: main
    defaultContentLanguage: true  # 기본 언어로 설정

  en:
    languageName: "English"
    languageCode: "en"
    weight: 2
    contentDir: "content/en"
    title: "My Site (English)"
    menu: main
