en:
  languageName: "English"
  weight: 1
  contentDir: "content/en"
  languageCode: "en"
  title: "My Site (English)"

ko:
  languageName: "Korean"
  weight: 2
  contentDir: "content/ko"
  languageCode: "ko"
  title: "내 사이트 (한국어)"
