# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language English
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
    title: My Portfolio
  params:
    description: My personal portfolio website in English.
  menu:
    main:
      - name: Park TaeHo
        url: '#about'
        weight: 1
# Uncomment the lines below to configure your website in a second language.
ko:
  languageCode: ko-kr
  contentDir: content/ko
  title: 나의 포트폴리오
  params:
    description: 나의 개인 포트폴리오 웹사이트.
  menu:
    main:
      - name: 박태호
        url: '#about'
        weight: 1
