main:
  - name: "Home"
    url: "/"
    weight: 1
  - name: "About"
    url: "/about"
    weight: 2
  - name: "People"
    url: "/people"
    weight: 3
    children:
      - name: "Professor"
        url: "/author/이경수/"
        weight: 1
      - name: "Members"
        url: "/people"
        weight: 2
  - name: "Research"
    url: "/research"
    weight: 4
