main:
  - name: "About"
    url: "/about"
    weight: 1

  - name: "People"
    url: "/people"
    weight: 2
  - parent: "People"
    name: "Professor"
    url: "/author/professor"
    weight: 3
  - parent: "People"
    name: "Members"
    url: "/people/members"
    weight: 4

  - name: "Research"
    url: "/research"
    weight: 5

  - name: "Contact"
    url: "/contact"
    weight: 6
