# Navigation Links
main:
  # Home은 주석 처리되어 있으므로 사용하지 않음
  # - name: Home
  #   url: /
  #   weight: 1
  
  # About
  - name: About
    url: /about/
    weight: 100

  # People 메뉴와 서브메뉴
  - name: People
    url: /people/
    weight: 200
  - parent: People
    name: Professor
    url: /author/이경수/
    weight: 210
  - parent: People
    name: Members
    url: /people/
    weight: 220

  # Research 메뉴와 서브메뉴
  - name: Research
    url: /publication/
    weight: 300
  - parent: Research
    name: Publications
    url: /publication/
    weight: 310
  - parent: Research
    name: Research Fields
    url: /field/
    weight: 320

  # Projects (주석 처리된 상태)
  # - name: Projects
  #   url: /project/
  #   weight: 400

  # Coursework (주석 처리된 상태)
  # - name: Coursework
  #   url: /publication/
  #   weight: 500

  # Inform 메뉴와 서브메뉴
  - name: Inform
    url: /post/
    weight: 600
  - parent: Inform
    name: Notifications
    url: /notification/
    weight: 610
  - parent: Inform
    name: News
    url: /post/
    weight: 620
  - parent: Inform
    name: Event
    url: /event/
    weight: 630

  # Contact
  - name: Contact
    url: /contact/
    weight: 700
