menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1  # 홈 페이지는 루트 경로를 사용
    - name: "About"
      url: "/about"  # 내부 페이지 경로
      weight: 2
    - name: "People"
      url: "/people"
      weight: 3
      children:
        - name: "Professor"
          url: "/author/professor"  # 내부 링크
          weight: 1
        - name: "Members"
          url: "/people/members"  # 내부 링크
          weight: 2
