# config.toml

[menu]
  [[menu.main]]
    name = "홈"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "소개"
    url = "/#intro"
    weight = 2

  [[menu.main]]
    name = "교육 과정"
    url = "/#education"
    weight = 3

  [[menu.main]]
    name = "기술"
    url = "/#skills"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5
