en:
  main:
    - name: "About"
      url: "/about"
      weight: 1

    - name: "People"
      url: "/people"
      weight: 2
      children:
        - name: "Professor"
          url: "/author/professor"
          weight: 3
        - name: "Members"
          url: "/people/members"
          weight: 4

    - name: "Research"
      url: "/research"
      weight: 5

    - name: "Contact"
      url: "/contact"
      weight: 6

ko:
  main:
    - name: "소개"
      url: "/about"
      weight: 1

    - name: "사람들"
      url: "/people"
      weight: 2
      children:
        - name: "교수님"
          url: "/author/professor"
          weight: 3
        - name: "회원들"
          url: "/people/members"
          weight: 4

    - name: "연구"
      url: "/research"
      weight: 5

    - name: "연락처"
      url: "/contact"
      weight: 6
