main:
  - name: "About"
    url: "/about"
    weight: 1

  - name: "People"
    url: "/people"
    weight: 2

  - name: "Research"
    url: "/research"
    weight: 3

  - name: "Contact"
    url: "/contact"
    weight: 4
