menus:
  main:
    - name: "About"
      url: "/about"
      weight: 1
    - name: "People"
      url: "/people"
      weight: 2
    - name: "Research"
      url: "/research"
      weight: 5
    - name: "Contact"
      url: "/contact"
      weight: 6

languages:
  en:
    languageName: "English"
    weight: 1
    menus:
      main:
        - name: "About"
          url: "/about"
          weight: 1
        - name: "People"
          url: "/people"
          weight: 2
        - name: "Research"
          url: "/research"
          weight: 5
        - name: "Contact"
          url: "/contact"
          weight: 6

  ko:
    languageName: "한국어"
    weight: 2
    menus:
      main:
        - name: "소개"
          url: "/about"
          weight: 1
        - name: "사람들"
          url: "/people"
          weight: 2
        - name: "연구"
          url: "/research"
          weight: 5
        - name: "연락처"
          url: "/contact"
          weight: 6
