menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "About (KR)"
      url: "/ko/about/"
      weight: 100

    - name: "About (EN)"
      url: "/en/about/"
      weight: 110

    - name: "Profile"
      url: "/profile/"
      weight: 200

    - name: "Biography"
      parent: "Profile"
      url: "/profile/biography/"
      weight: 210

    - name: "Skills"
      parent: "Profile"
      url: "/profile/skills/"
      weight: 220

    - name: "Projects"
      url: "/projects/"
      weight: 300

    - name: "Portfolio"
      parent: "Projects"
      url: "/projects/portfolio/"
      weight: 310

    - name: "Research Fields"
      parent: "Projects"
      url: "/projects/research-fields/"
      weight: 320

    - name: "Research"
      url: "/research/"
      weight: 400

    - name: "Publications"
      parent: "Research"
      url: "/research/publications/"
      weight: 410

    - name: "Fields of Study"
      parent: "Research"
      url: "/research/fields/"
      weight: 420

    - name: "Contact"
      url: "/contact/"
      weight: 500
