main:
  - name: Home
    url: /
    weight: 1

  - name: 소개
    url: /#intro
    weight: 2

  - name: 교육 과정
    url: /#education
    weight: 3

  - name: 기술
    url: /#skills
    weight: 4

  - name: Contact
    url: /contact
    weight: 5
