main:
  - name: About
    url: /about/
    weight: 1

  - name: Information
    url: /information/
    weight: 2

  - name: Project
    url: /project/
    weight: 3
  - parent: Project
    name: Goal
    url: /project/goal/
    weight: 310
  - parent: Project
    name: Process
    url: /project/process/
    weight: 320

  - name: AI
    url: /ai/
    weight: 4

  - name: Contact
    url: /contact/
    weight: 5
